"""Add IncidentDutyORM for incident-duty relationships + add created_at to duties table

Revision ID: ba7d1de52dc4
Revises:
Create Date: 2025-10-12 20:32:19.655100

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba7d1de52dc4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devopses",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("telegram_username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("id", sa.Uuid(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_username"),
    )
    op.create_table(
        "incidents",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="incidentpriority"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "duties",
        sa.Column("devops_id", sa.Uuid(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["devops_id"],
            ["devopses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "incident_duty",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("duty_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("assigned_by", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["devopses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["duty_id"],
            ["duties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("incident_duty")
    op.drop_table("duties")
    op.drop_table("incidents")
    op.drop_table("devopses")
    # ### end Alembic commands ###
